### ISSUE TITLE
Check given number of requests instead of one at the same time?

### ISSUE THREAD

**Issue by Lovesmoring** [ulule/limiter#117]
Hi,

Is it simple and necessary to add something like AllowN functionality like the other rate limiter instead of just Get to check a single request? 
For example, in my case, I want to put a rate limit on the accumulated batch size of a list inside one request, rather than on the number of requests.

And another suggestion is that since the user can specify their key for this limiter for example API keys instead of IP, it is maybe good to point this out in example code or README.

Thanks

**Comment by novln** [comment]
Hello :wave: 

I have a few question, for the `AllowN` feature. Let's say you would like to acquire N requests, and X being the remaining requests. If `N > X`, do you want the overflow to be allowed, or simply reject the whole bulk because there is an insufficient number of remaining requests ?

For the second point about the documentation, it's a good point. When I'll have time, I'll add it. But in the meantime, don't hesitate to submit a pull requests.

Cheers,

**Comment by novln** [comment]
Closing since there is no update on this issue.
