### ISSUE TITLE
Feature Request: Please can you add rqlite as store 

### ISSUE THREAD

**Issue by git001** [ulule/limiter#179]
As https://github.com/rqlite/rqlite/ is a quite robust and easy to setup distributed database how about to add it as a store similar to redis.
There is a ready to use go library https://github.com/rqlite/gorqlite which could make the integration not to difficult.

Maybe you can create a How To for a store integration so that some other developer can try to create a driver for the rqlite store.

**Comment by novln** [comment]
Hello,

I'll not create a new driver for `rqlite` since I don't have time and I don't want to maintain it.
However, I could gladly help you create you own driver. I thought it was quite obvious, but maybe not...

Your store just have to implement this interface: https://github.com/ulule/limiter/blob/c5200d831926a0d9057f870b2b670efffe2cbf74/store.go#L9

You can find inspiration with the redis store here: https://github.com/ulule/limiter/blob/c5200d831926a0d9057f870b2b670efffe2cbf74/drivers/store/redis/store.go#L84

Don't hesitate if you need anything else.

Cheers,

**Comment by thoas** [comment]
Hi, we don't provide additional features than what we need internally, so if you want a particular driver go send a PR, we will review it.
