### ISSUE TITLE
A key can be limited forever

### ISSUE THREAD

**Issue by nguyenlh253** [ulule/limiter#233]
I saw _luaIncrScript_ in redis store, then i read a blog in redis (https://redis.com/glossary/rate-limiting/). At the end of this blog, there are paragraph 
<img width="1234" alt="image" src="https://github.com/ulule/limiter/assets/134992223/5657d797-fbc1-48d8-aa89-bc48c01a2a8e">
I find _luaIncrScript_ have the same problem. Can we add **_an auto recovery way_** to fix it with a new luaIncrScript:
```
newLuaIncrScript = 
local key = KEYS[1]
local count = tonumber(ARGV[1])
local ttl = tonumber(ARGV[2])
local limit = tonumber(ARGV[3])
local ret = redis.call("incrby", key, ARGV[1])
if ret == count then
	if ttl > 0 then
		redis.call("pexpire", key, ARGV[2])
	end
	return {ret, ttl}
end
if ret > limit then
	redis.call("pexpire", key, ARGV[3])
end
ttl = redis.call("pttl", key)
return {ret, ttl}
```
But the new script will cause an key limited continously. For example: if we set limit is 5, period is 1s and the limit is reached at 800ms, but we continue hitting, the reset time will be added a period per a hitting time.

**Comment by novln** [comment]
Hello,

I'm sorry, what's the issue ? If it was:

> When restoring either from an AOF or in-memory replication, the INCR will not be restored since the transaction was not complete.

Then it's not an issue since the "transaction" was not committed. If I'm not mistaken, an error will be returned in the redis drivers layer. Then, the middleware could decide if we want to allow (or not) requests in this case of failure.

If your middleware decide to not accept requests, then no worries, when your redis server is up again it will continue counting from here it was before the "transaction" was not complete.

Or am I missing something ?

**Comment by nguyenlh253** [comment]
I have tested crashing server during low lua script, it really likes you say (transaction has yet committed). But in redis site, they say **_in worse-case_**, a key can't be set expire time, so an user can have two keys (means a key cann't be set expire time). I have just used your lib, and i see the problem (maybe) in your lua script mentioned in redis site so i raise up. I really find everything normal in theory, but I worry about the worse-case can be happenned. I will give you my feedback after I use it for a long time
